name: DEC
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - hdbscan
  - dash
  - pyarrow
  - xgboost
  - pip:
      - torch>=2.0
      - gower
      - miceforest
